### ISSUE TITLE
Install Error: create temp dir failed

### ISSUE THREAD

**Issue by PikuZheng** [tiann/KernelSU#1508]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

尝试安装时提示 
Install Error: create temp dir failed

### To Reproduce

1. 点击安装
2.  选择一个文件（没有其他选项）
3.  选择原厂boot.img
4.  下一步

### Logs

```
03-22 09:44:55.556 10304 10304 I KernelSU: ksud::cli: command: Debug { command: Su { global_mnt: false } }
03-22 09:44:55.557 10304 10304 E KernelSU: ksud::cli: Error: grant root failed
03-22 09:44:55.558  8435  8517 E KsuCli  : su failed: 
03-22 09:44:55.558  8435  8517 E KsuCli  : h2.b: Unable to create a shell!
03-22 09:44:55.558  8435  8517 E KsuCli  : 	at j3.E.m(Unknown Source:47)
03-22 09:44:55.558  8435  8517 E KsuCli  : 	at O2.j.D(Unknown Source:53)
03-22 09:44:55.558  8435  8517 E KsuCli  : 	at Z2.M.s(Unknown Source:277)
03-22 09:44:55.558  8435  8517 E KsuCli  : 	at x2.a.l(Unknown Source:8)
03-22 09:44:55.558  8435  8517 E KsuCli  : 	at M2.F.run(Unknown Source:114)
03-22 09:44:55.558  8435  8517 E KsuCli  : 	at N2.c.run(Unknown Source:12)
03-22 09:44:55.558  8435  8517 E KsuCli  : 	at S2.j.run(Unknown Source:2)
03-22 09:44:55.558  8435  8517 E KsuCli  : 	at S2.a.run(Unknown Source:95)
03-22 09:44:55.558  8435  8517 E KsuCli  : Caused by: java.io.IOException: Created process is not a shell
03-22 09:44:55.558  8435  8517 E KsuCli  : 	at i2.f.call(Unknown Source:182)
03-22 09:44:55.558  8435  8517 E KsuCli  : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-22 09:44:55.558  8435  8517 E KsuCli  : 	at i2.B.call(Unknown Source:19)
03-22 09:44:55.558  8435  8517 E KsuCli  : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-22 09:44:55.558  8435  8517 E KsuCli  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-22 09:44:55.558  8435  8517 E KsuCli  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-22 09:44:55.558  8435  8517 E KsuCli  : 	at java.lang.Thread.run(Thread.java:920)
03-22 09:44:55.571 10313 10313 I KernelSU: ksud::cli: command: BootPatch { boot: Some("/data/user/0/me.weishu.kernelsu/cache/boot.img"), kernel: None, module: None, init: None, ota: false, flash: false, out: Some("/storage/emulated/0/Download"), magiskboot: Some("/data/app/~~GmegrsAD8NxHxWYkBmIlJQ==/me.weishu.kernelsu-KUbLwXAfW5NiQsihGUEo8Q==/lib/arm64/libmagiskboot.so"), kmi: None }
03-22 09:44:55.573 10313 10313 E KernelSU: ksud::cli: Error: create temp dir failed
03-22 09:44:55.573 10313 10313 E KernelSU: 
03-22 09:44:55.573 10313 10313 E KernelSU: Caused by:
03-22 09:44:55.573 10313 10313 E KernelSU:     Permission denied (os error 13)
03-22 09:44:55.575  8435  8517 I KernelSU: install boot result: false
```

### Device info

- Device: Oneplus 10 pro
- OS Version: ColorOS 12.1
- KernelSU Version: v0.9.2(11682)
- Kernel Version: N/A

**Comment by PikuZheng** [comment]
系统当前有 magisk root，但没有收到 root 权限请求

**Comment by YlarodAli** [comment]
目前该功能只支持 KernelSU，不支持 MagiskSU

**Comment by PikuZheng** [comment]
用0.9.0修补boot刷入，在 0.9.2的管理器依然没有lkm安装方式，是不是意味着它不支持 😭
