### ISSUE TITLE
Install Error: create temp dir failed

### ISSUE THREAD

**Issue by Haodadeyuang** [tiann/KernelSU#1852]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

在安装boot时候提示
Error: create temp dir failed
Caused by:
    Permission denied (os error 13)

### Logs

Error: create temp dir failed

Caused by:
    Permission denied (os error 13)
  _  __                    _ ____  _   _ 
 | |/ /___ _ __ _ __   ___| / ___|| | | |
 | ' // _ \ '__| '_ \ / _ \ \___ \| | | |
 | . \  __/ |  | | | |  __/ |___) | |_| |
 |_|\_\___|_|  |_| |_|\___|_|____/ \___/ 

- Install Error: create temp dir failed

### Device info

- Device: 红米K50
- OS Version: MIUI 13.0.16和13.0.21
- KernelSU Version: 1.0.0
- Kernel Version:

### Additional context

开发者你好，我在尝试安装boot时候提示了上述错误。
已经给了所有权限到ksu，线刷了多个版本的miui均有该错误，boot文件无论是卡刷包还是线刷包提取出来的都不行，BL锁已解。
![报错](https://github.com/tiann/KernelSU/assets/57080327/fcff013e-f36e-4d8c-8736-904fb3a5bf4b)
![内核版本](https://github.com/tiann/KernelSU/assets/57080327/95fbce09-e426-4ae4-b57d-12152a7d8ee0)

**Comment by tiann** [comment]
右上角有个保存按钮，请点一下然后把这个日志上传上来。

**Comment by Haodadeyuang** [comment]
[KernelSU_install_log_2024-07-04-18-27-49.log](https://github.com/user-attachments/files/16101244/KernelSU_install_log_2024-07-04-18-27-49.log)

> 右上角有个保存按钮，请点一下然后把这个日志上传上来。

**Comment by Haodadeyuang** [comment]
> 右上角有个保存按钮，请点一下然后把这个日志上传上来。

您好，日志见上层回复，但我一开始看过了，日志内容其实已经全部在issues正文里了，只有一点点。

**Comment by xinyudashen** [comment]
redmi note11tpro miui13.0.13，一样的报错

**Comment by srdr0p** [comment]
Same error on Pixel 6 (already has aosp su):

**Comment by srdr0p** [comment]
> Same error on Pixel 6 (already has aosp su):

08-14 12:41:53.612  3971  3971 I KernelSU: ksud::cli: command: Debug { command: Su { global_mnt: false } }
08-14 12:41:53.612  3971  3971 E KernelSU: ksud::cli: Error: Operation not permitted (os error 1)
08-14 12:41:53.612  3778  3819 W KsuCli  : ksu failed:
08-14 12:41:53.612  3778  3819 W KsuCli  : l2.b: Unable to create a shell!
08-14 12:41:53.612  3778  3819 W KsuCli  :      at F1.h.h(Unknown Source:58)
08-14 12:41:53.612  3778  3819 W KsuCli  :      at F1.h.f(Unknown Source:6)
08-14 12:41:53.612  3778  3819 W KsuCli  :      at U0.b.z(Unknown Source:43)
08-14 12:41:53.612  3778  3819 W KsuCli  :      at U0.b.E(Unknown Source:13)
08-14 12:41:53.612  3778  3819 W KsuCli  :      at i3.N.t(Unknown Source:322)
08-14 12:41:53.612  3778  3819 W KsuCli  :      at D2.a.m(Unknown Source:8)
08-14 12:41:53.612  3778  3819 W KsuCli  :      at U2.F.run(Unknown Source:114)
08-14 12:41:53.612  3778  3819 W KsuCli  :      at V2.c.run(Unknown Source:25)
08-14 12:41:53.612  3778  3819 W KsuCli  :      at b3.k.run(Unknown Source:2)
08-14 12:41:53.612  3778  3819 W KsuCli  :      at b3.a.run(Unknown Source:95)
08-14 12:41:53.612  3778  3819 W KsuCli  : Caused by: java.io.IOException: Created process is not a shell
08-14 12:41:53.612  3778  3819 W KsuCli  :      at m2.z.call(Unknown Source:182)
08-14 12:41:53.612  3778  3819 W KsuCli  :      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-14 12:41:53.612  3778  3819 W KsuCli  :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-14 12:41:53.612  3778  3819 W KsuCli  :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-14 12:41:53.612  3778  3819 W KsuCli  :      at java.lang.Thread.run(Thread.java:920)
08-14 12:41:53.613  3778  3819 E KsuCli  : su failed:
08-14 12:41:53.613  3778  3819 E KsuCli  : l2.b: Unable to create a shell!
08-14 12:41:53.613  3778  3819 E KsuCli  :      at F1.h.h(Unknown Source:65)
08-14 12:41:53.613  3778  3819 E KsuCli  :      at F1.h.f(Unknown Source:6)
08-14 12:41:53.613  3778  3819 E KsuCli  :      at U0.b.z(Unknown Source:78)
08-14 12:41:53.613  3778  3819 E KsuCli  :      at U0.b.E(Unknown Source:13)
08-14 12:41:53.613  3778  3819 E KsuCli  :      at i3.N.t(Unknown Source:322)
08-14 12:41:53.613  3778  3819 E KsuCli  :      at D2.a.m(Unknown Source:8)
08-14 12:41:53.613  3778  3819 E KsuCli  :      at U2.F.run(Unknown Source:114)
08-14 12:41:53.613  3778  3819 E KsuCli  :      at V2.c.run(Unknown Source:25)
08-14 12:41:53.613  3778  3819 E KsuCli  :      at b3.k.run(Unknown Source:2)
08-14 12:41:53.613  3778  3819 E KsuCli  :      at b3.a.run(Unknown Source:95)
08-14 12:41:53.613  3778  3819 E KsuCli  : Caused by: java.io.IOException: Cannot run program "su": error=13, Permission denied
08-14 12:41:53.613  3778  3819 E KsuCli  :      at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
08-14 12:41:53.613  3778  3819 E KsuCli  :      at java.lang.Runtime.exec(Runtime.java:694)
08-14 12:41:53.613  3778  3819 E KsuCli  :      at java.lang.Runtime.exec(Runtime.java:559)
08-14 12:41:53.613  3778  3819 E KsuCli  :      at F1.h.h(Unknown Source:11)
08-14 12:41:53.613  3778  3819 E KsuCli  :      ... 9 more
08-14 12:41:53.613  3778  3819 E KsuCli  : Caused by: java.io.IOException: error=13, Permission denied
08-14 12:41:53.613  3778  3819 E KsuCli  :      at java.lang.UNIXProcess.forkAndExec(Native Method)
08-14 12:41:53.613  3778  3819 E KsuCli  :      at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
08-14 12:41:53.613  3778  3819 E KsuCli  :      at java.lang.ProcessImpl.start(ProcessImpl.java:141)
08-14 12:41:53.613  3778  3819 E KsuCli  :      at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
08-14 12:41:53.613  3778  3819 E KsuCli  :      ... 12 more
08-14 12:41:53.626  3976  3976 I KernelSU: ksud::cli: command: BootPatch { boot: Some("/data/user/0/me.weishu.kernelsu/cache/boot.img"), kernel: None, module: None, init: None, ota: false, flash: false, out: Some("/storage/emulated/0/Download"), magiskboot: Some("/data/app/~~kSo0t3kbL6Bzlay4-FXrXA==/me.weishu.kernelsu--xhSiYKpB5T_PmrOwxitmA==/lib/arm64/libmagiskboot.so"), kmi: None }
08-14 12:41:53.626  3976  3976 E KernelSU: ksud::cli: Error: create temp dir failed
08-14 12:41:53.626  3976  3976 E KernelSU:
08-14 12:41:53.626  3976  3976 E KernelSU: Caused by:
08-14 12:41:53.626  3976  3976 E KernelSU:     Permission denied (os error 13)
08-14 12:41:53.627  3778  3819 I KernelSU: install boot result: false

**Comment by silasol** [comment]
When I use kernelsu on A12, the same error occurs. 
When I switch to the Rom of A13, everything is normal.

**Comment by yuji01** [comment]
## I also encountered this problem, but I solved it like this

> Tests found that this version does not support LKM kernelSU, but supports GKI version of KernelSU
> Temporary startup is no problem, but once flashed, it cannot be started
> After testing, it was found that it was an AVB verification problem. The following is the solution

Available GKI version: [android12-5.10.198_2024-01-boot.img.gz](https://github.com/tiann/KernelSU/releases/download/v1.0.1/android12-5.10.198_2024-01-boot.img.gz)

How to use: Unzip the file, and then flash the img in fastboot mode

1. Temporary startup img (restart invalid): `fastboot boot kernel_file`
2. After restarting, the phone has temporary root permissions, then install **Hardware Assistant**

> If you click Install in KernelSU and install it directly, what is actually installed is LKM version
> Click to patch the image, which is also the LKM version
> Click to install to an unused slot, which is also the LKM version

1. Use kernelSU to grant root permissions to the Gear Assistant, then open the Gear Assistant
2. `ROOT Zone` -> `Disable AVB2.0 boot verification/DM verification` -> `3Disable AVB2.0 boot verification/DM verification`
3. After that, restart the phone and flash the kernel normally
4. Flash the kernel: `fastboot flash boot kernel_file`

Now, my phone works normally and the version is GKI. If you don't need GKI, the above steps have actually solved this problem ; )

**Comment by Xiaoxuehaimeibiyene** [comment]
同是 K50 MIUI 13.0.13.0，但是问题已自行解决。
建议：
1. 先用 adb-fastboot 成功刷入 v0.9.0 中的 `boot-gz.img.gz`，并安装最新版本的 KernelSU 管理器即 ksu apk；
2. 打开 KernelSU 管理器，右上角“安装” - “选择一个文件”，选择你那个版本的官方系统包里提取的 `boot.img`，生成一个 patched img；
3. 用 adb-fastboot 刷入此 patched img。

**Comment by tiann** [comment]
出现这个问题的原因是：管理器无法访问 /sdcard/Download 目录。
