### ISSUE TITLE
【WEBUI】API中 spawn 方法不生效

### ISSUE THREAD

**Issue by powerAn2020** [tiann/KernelSU#2064]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [x] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

```javascript
import { spawn } from 'kernelsu';

const ls = spawn('ls', ['-lh', '/data']);

ls.stdout.on('data', (data) => {
  debugger;
  console.log(`stdout: ${data}`);
});

ls.stderr.on('data', (data) => {
  debugger;
  console.log(`stderr: ${data}`);
});

ls.on('exit', (code) => {
  debugger;
  console.log(`child process exited with code ${code}`);
});
```
上述代码抄的npm文档，加了  `debugger`，在MIUI和原生安卓中都试过,但是始终无法进入断点。

### Expected behavior

进入断点

### Device info

![image](https://github.com/user-attachments/assets/deae369d-dfe3-40e1-85be-96ce9d9e5be8)

**Comment by whalechoi** [comment]
```
09-21 12:36:22.544 31247 31498 W System.err: org.json.JSONException: Value ["-lh","\/data"] of type org.json.JSONArray cannot be converted to JSONObject
09-21 12:36:22.544 31247 31498 W System.err: 	at org.json.JSON.typeMismatch(JSON.java:112)
09-21 12:36:22.544 31247 31498 W System.err: 	at org.json.JSONObject.<init>(JSONObject.java:172)
09-21 12:36:22.544 31247 31498 W System.err: 	at org.json.JSONObject.<init>(JSONObject.java:185)
09-21 12:36:22.544 31247 31498 W System.err: 	at p3.i.a(Unknown Source:10)
09-21 12:36:22.544 31247 31498 W System.err: 	at p3.i.spawn(Unknown Source:20)
09-21 12:36:22.544 31247 31498 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
09-21 12:36:22.544 31247 31498 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:359)
09-21 12:36:22.544 31247 31498 W System.err: 	at android.os.Looper.loopOnce(Looper.java:187)
09-21 12:36:22.544 31247 31498 W System.err: 	at android.os.Looper.loop(Looper.java:364)
09-21 12:36:22.544 31247 31498 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:67)
09-21 12:36:22.552  4444  4444 I KernelSU: ksud::cli: command: Debug { command: Su { global_mnt: true } }
```

**Comment by whalechoi** [comment]
![1](https://github.com/user-attachments/assets/00acf5bd-15a5-405e-909d-ac4d8d15a52c)
![2](https://github.com/user-attachments/assets/ea8a8a34-e88f-4f73-9ef9-f3cd3ad51b38)

这个问题 #1395 已经修了，不过要等 1.0.7 发布了
