### ISSUE TITLE
Manager crashes within seconds of switching to the modules tab

### ISSUE THREAD

**Issue by xueshiji** [tiann/KernelSU#367]
**Describe the bug**
Manager crashes within seconds of switching to the modules tab

**To Reproduce**
1.Switching to the modules tab
2.Wait a few seconds
3.Crash

**Expected behavior**
not crash

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: RedMI K40s
 - OS: MIUI 14.0.23.4.2.DEV
 - Version [0.5.1]

**Additional context**
Trace:
java.lang.IllegalStateException: Asking for measurement result of unmeasured layout modifier
	at f1.o0.b1(Unknown Source:13)
	at f1.x.S0(Unknown Source:40)
	at d1.r0$a.d(Unknown Source:32)
	at f1.e0$b$b.G(Unknown Source:19)
	at k0.h$a.a(Unknown Source:63)
	at k0.a0.G(Unknown Source:6)
	at androidx.activity.o.B0(Unknown Source:43)
	at f1.h1.a(Unknown Source:74)
	at f1.e0$b.Y0(Unknown Source:64)
	at f1.e0$b.S0(Unknown Source:49)
	at d1.r0$a.c(Unknown Source:40)
	at m.k1$a.d0(Unknown Source:115)
	at d1.e0$a.f(Unknown Source:39)
	at f1.e0$b$a.G(Unknown Source:99)
	at k0.h$a.a(Unknown Source:63)
	at k0.a0.G(Unknown Source:6)
	at androidx.activity.o.B0(Unknown Source:43)
	at f1.h1.a(Unknown Source:74)
	at f1.e0$b.C(Unknown Source:123)
	at f1.r.S0(Unknown Source:126)
	at d1.r0$a.e(Unknown Source:74)
	at m.v$a.d0(Unknown Source:10)
	at d1.e0$a.f(Unknown Source:39)
	at f1.x.S0(Unknown Source:44)
	at d1.r0$a.d(Unknown Source:32)
	at f1.e0$b$b.G(Unknown Source:19)
	at k0.h$a.a(Unknown Source:63)
	at k0.a0.G(Unknown Source:6)
	at androidx.activity.o.B0(Unknown Source:43)
	at f1.h1.a(Unknown Source:74)
	at f1.e0$b.Y0(Unknown Source:64)
	at f1.e0$b.S0(Unknown Source:49)
	at d1.r0$a.c(Unknown Source:40)
	at m.k1$a.d0(Unknown Source:115)
	at d1.e0$a.f(Unknown Source:39)
	at f1.e0$b$a.G(Unknown Source:99)
	at k0.h$a.a(Unknown Source:63)
	at k0.a0.G(Unknown Source:6)
	at androidx.activity.o.B0(Unknown Source:43)
	at f1.h1.a(Unknown Source:74)
	at f1.e0$b.C(Unknown Source:123)
	at f1.r.S0(Unknown Source:126)
	at d1.r0$a.e(Unknown Source:74)
	at m.v$a.d0(Unknown Source:10)
	at d1.e0$a.f(Unknown Source:39)
	at f1.x.S0(Unknown Source:44)
	at d1.r0$a.d(Unknown Source:32)
	at f1.e0$b$b.G(Unknown Source:19)
	at k0.h$a.a(Unknown Source:63)
	at k0.a0.G(Unknown Source:6)
	at androidx.activity.o.B0(Unknown Source:43)
	at f1.h1.a(Unknown Source:74)
	at f1.e0$b.Y0(Unknown Source:64)
	at f1.z.U(Unknown Source:26)
	at f1.i0.j(Unknown Source:206)
	at f1.i0.f(Unknown Source:68)
	at androidx.compose.ui.platform.AndroidComposeView.b(Unknown Source:13)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(Unknown Source:20)
	at android.view.View.draw(View.java:23331)
	at android.view.View.updateDisplayListIfDirty(View.java:22187)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4527)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4500)
	at android.view.View.updateDisplayListIfDirty(View.java:22139)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4527)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4500)
	at android.view.View.updateDisplayListIfDirty(View.java:22139)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4527)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4500)
	at android.view.View.updateDisplayListIfDirty(View.java:22139)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4527)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4500)
	at android.view.View.updateDisplayListIfDirty(View.java:22139)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:795)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4823)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4524)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3738)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2476)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9331)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1390)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1398)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1040)
	at android.view.Choreographer.doFrame(Choreographer.java:954)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1370)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8116)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

[KernelSU_bugreport_2023-04-11_12_13.tar.gz](https://github.com/tiann/KernelSU/files/11196724/KernelSU_bugreport_2023-04-11_12_13.tar.gz)

**Comment by tiann** [comment]
Please install this : https://github.com/tiann/KernelSU/files/11207307/KernelSU_v0.5.1-12-g273a0b0-release.apk.zip And check it again

**Comment by xueshiji** [comment]
Add Steps to reproduce the behavior:
1.install the model:id=dc_backlight_fps,name=K40S开启DC调光和90Hz刷新率
2.This module causes bootloop
3.Rescue from bootloop
4.launch manager
5.Switching to the modules tab
6.Wait a few seconds
7.Crash
8.The manager will return to normal after uninstalling this module

By the way,the same goes for KernelSU_v0.5.1-17-g3c6560a-release.apk
Here is the module.
[K40S开启DC和90Hz选项(仅限安卓13 MIUI14).zip](https://github.com/tiann/KernelSU/files/11207590/K40S.DC.90Hz.13.MIUI14.zip)

**Comment by xueshiji** [comment]
Captured logs with KernelSU_v0.5.1-17-g3c6560a-release.apk:
[KernelSU_bugreport_2023-04-12_13_39.tar.gz](https://github.com/tiann/KernelSU/files/11207643/KernelSU_bugreport_2023-04-12_13_39.tar.gz)

**Comment by tiann** [comment]
please send the bugreport
